#!/usr/bin/env node
'use strict';

const fs = require('fs');
const readline = require('readline');
const chalk = require('chalk');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(resolve => rl.question(q, resolve));

async function setup() {
  console.log(chalk.bold.blue('\n SEO Indexing Agent — Setup Wizard\n'));
  console.log(chalk.gray('This will create your .env file with all required credentials.\n'));

  const siteUrl = await ask('Your website URL (e.g. https://mysite.com): ');
  const githubRepo = await ask('GitHub repo (owner/repo, or press Enter to skip): ');
  const githubToken = await ask('GitHub personal access token (for pushing fixes, or Enter to skip): ');
  const keyPath = await ask('Path to Google service account JSON key (or Enter to skip): ');

  const env = `# SEO Indexing Agent — generated by setup wizard
SITE_URL=${siteUrl.trim()}
GITHUB_REPO=${githubRepo.trim()}
GITHUB_TOKEN=${githubToken.trim()}
GITHUB_BRANCH=main
GOOGLE_SERVICE_ACCOUNT_KEY_PATH=${keyPath.trim() || './config/service-account.json'}
MAX_CRAWL_PAGES=1000
CRAWL_DELAY_MS=500
AUTO_SUBMIT=true
`;

  fs.writeFileSync('.env', env);
  console.log(chalk.green('\n✓ .env file created\n'));

  if (!keyPath.trim()) {
    console.log(chalk.yellow('Google credentials not set. To enable auto-submission:'));
    console.log(chalk.gray('1. Go to console.cloud.google.com'));
    console.log(chalk.gray('2. Create a Service Account with "Web Search Console" access'));
    console.log(chalk.gray('3. Download the JSON key'));
    console.log(chalk.gray('4. Add path to GOOGLE_SERVICE_ACCOUNT_KEY_PATH in .env\n'));
  }

  console.log(chalk.bold('Ready! Run:'));
  console.log(chalk.cyan('  node src/index.js run --url ' + siteUrl.trim() + '\n'));

  rl.close();
}

setup().catch(err => { console.error(err); process.exit(1); });
